local GSE = GSE
local Statics = GSE.Static

Statics.Patrons = {
    "'William Meringolo",
    "1990Causer",
    "900obzen ",
    "A Four",
    "AJ Guckian",
    "AL",
    "ARTEX",
    "Aabukim",
    "Aamir Shakir",
    "Aaron Halpin",
    "Aaron Smith",
    "Aaron Steley",
    "Acromion",
    "Adaestra ",
    "Adam Anderson",
    "Adam Doherty",
    "Adam Fisher",
    "Adam Tall",
    "Adrian Cornelius",
    "Adrian Maier",
    "Adventures Of Raven",
    "Aiden Gramson",
    "Akk",
    "Alejandro Sanclemente",
    "Alex",
    "Alex Branch",
    "Alexander Verrecchia",
    "Alfred Green",
    "Allan Korsgaard",
    "Allan Smith Nielsen",
    "Allen Ponce",
    "Andre Carbonell",
    "Andrea Rossi",
    "Andrew Baldwin",
    "Andrew Fox",
    "Andrew Lester",
    "Andrew VanArman",
    "Andris Kulmans",
    "Andy Dalmat",
    "Andy Erickson",
    "Angel Marchini",
    "Angrypug",
    "AnjosRodrigo",
    "Anthony",
    "Antti Rautio",
    "Anubikk ",
    "Arne Krüger",
    "Ashley",
    "Ashley Ludwig",
    "Ashneel Kumar",
    "Austin Crain",
    "Axellis ",
    "BAO D LE",
    "BRIAN V DELLER",
    "Baely ",
    "Baka Pixel",
    "Bear",
    "Bearded_Gamer ",
    "Becan",
    "Bella RH",
    "Ben Hocking",
    "Ben Stage",
    "Bengt Grahl",
    "Bennyfof",
    "Beta",
    "Bghy Rbfch",
    "BigPoppaRich",
    "Big_Al",
    "Billy ",
    "Binary Nick",
    "Bitto",
    "Biyanshi",
    "Bob",
    "Bobbi Queen",
    "Brad ",
    "Brandon Bks",
    "Brandon Conklin",
    "Brandon Crose",
    "Brett Warfle",
    "Brian",
    "Brian Dickerson",
    "Brian Lewin",
    "Brian Lynch",
    "Brian Miller",
    "Bruce Wardle",
    "Bryan Burns",
    "Bryan Ingram",
    "Bryan Seitz",
    "Burt Reynolds",
    "Cabiria-Il-Notte ",
    "Calvin Jones",
    "Card Cracking Chef",
    "Carlos Alberto Arizpe Mendoza",
    "Carter Cross",
    "Cdub3n",
    "Charles",
    "Charles R Tabor",
    "Chase Hoppock",
    "Choco Munday",
    "Chris",
    "Chris Bunting",
    "Chris Cordwell",
    "Chris Esparza",
    "Chris G",
    "Chris Hynes",
    "Chris Jackson",
    "Chris Juengel",
    "Chris Livingston",
    "Christian Mostert",
    "Christopher Lee",
    "Christopher Young",
    "Christos ",
    "Codda Matl",
    "Colby Rooker",
    "Colm",
    "Constantin Martini",
    "Copy",
    "Corey Marchant",
    "Country Creations",
    "Cruelier",
    "DENNIS CHRISTENSEN",
    "DJ",
    "DJ_FingaGunz",
    "DMFerree",
    "Damon Walker",
    "Dan",
    "Dan Inda",
    "Daniel Clements",
    "Daniel Gabriele",
    "Daniel Kristofersson",
    "Daniel Lange",
    "Daniel Perez",
    "Daniel Sümmchen",
    "Daniel Thomas",
    "Darkane",
    "Darroll Howard",
    "Dave Gordon",
    "David Isburgh",
    "David Lobato",
    "David Rice",
    "David Rose",
    "David Thrower",
    "Deborah Gough",
    "Deezyl Fizzlepop",
    "Denis Samoilov",
    "Derik B Casper",
    "Devin Blair",
    "Diedora",
    "Dieter Cazon",
    "Dirk Kowalski",
    "Dirty Apparition",
    "Dominik Krabacher",
    "Donald Easter",
    "Donnie Spencer",
    "Doug Miers",
    "Dredd",
    "Drioz",
    "Drunk Gaming",
    "Dustin Davenport",
    "Dustin Gadd",
    "Dustin W",
    "E Peters",
    "Ed E",
    "Edgar Dazevedo",
    "Eduard Claassen",
    "Elange4 ",
    "ElderGod Games",
    "Elfyau",
    "Elgador",
    "Eli Sapanayev",
    "Emannuel ",
    "Emanuel Barbi",
    "Emo Mihov",
    "Enmity",
    "Envoy",
    "Eric Desmarais",
    "Eric Donini",
    "Eric Kerzman",
    "Eric Rainey",
    "Eric Roberts",
    "Eric Sanders",
    "Eric Stoeckel Jr",
    "Eric Vasquez",
    "Eric Vincent",
    "Eric donini",
    "Erich Herbert",
    "Erin Reymann",
    "Euben Hadd",
    "Eusélie",
    "Everett St.Clair",
    "Excutive Outcome game",
    "Eznoda",
    "FERDIN GONZALEZ",
    "FPSMarcus",
    "FUT_Sovereign ",
    "FaderBog",
    "Fadi Alfadda",
    "Fallens Death",
    "Fangorian_1337",
    "Fatality",
    "Ferat A",
    "Florin Enache",
    "Francisco Fernandez",
    "Frankie Lee",
    "FyuZ. ",
    "GamingMama56",
    "Gary",
    "Gary Markland",
    "GenTsoCkn ",
    "Gendi",
    "Geoff Weinhold",
    "Geoffrey Tang",
    "George McCubbins",
    "Gerald McCandless",
    "Gerardo Oduber",
    "Gianluca Berian",
    "Gilian Bentulan",
    "Glenn van Kooijk",
    "Goregoth",
    "Greg Schmitz",
    "Gregory ",
    "Gregory M",
    "Grifter",
    "Grim",
    "Grumpy British old Gamer",
    "Gustav Gans",
    "Gấu Panda",
    "Hannah Mae",
    "Hansli Peterli",
    "Hayden Dee",
    "Helder Fernandes",
    "Helios",
    "Henrik Nielsen",
    "Herbert Besenfelder",
    "Holger",
    "Holli Mcmillen",
    "Hollis Ford",
    "HomeMobileEmail",
    "Hong Shang",
    "Hugh Judd",
    "Indomitus B",
    "Isaiah Lombardy",
    "Ivan Chiu",
    "J G",
    "Jacek Pasławski",
    "Jack Etienne",
    "Jack Selektion",
    "Jacob Richey",
    "Jakob Andersen",
    "James Beck",
    "James Blamey",
    "James Faircloth",
    "James Turnbull",
    "James Webster",
    "Jamie Cuomo",
    "Jamie Currier",
    "Jani Kay",
    "JarrTET",
    "Jason ",
    "Jason Cartledge",
    "Jason Johnson",
    "Jason Kartes",
    "Jasper Hengefeld",
    "Jayson Isaacs",
    "Jean-Philippe Baril",
    "Jed Lawton",
    "Jeff Berman",
    "Jeff Butler",
    "Jeff Hughes",
    "Jeffrey White",
    "Jennifer Angelidis",
    "Jeremy Grayson",
    "Jeremy Harvey",
    "Jeremy Jones",
    "Jeremy Neumann",
    "Jerrod Linderman",
    "Jerry T",
    "Jessica",
    "Jim",
    "Jim B",
    "Jimmy Tuvebrant",
    "Jinazz",
    "Jodi Meese",
    "Joe Davis",
    "Joe Dinsmore",
    "Joe Jackson",
    "Joe Newitt",
    "Joel D Bailey",
    "Johan Andersson",
    "Johan Lindqvist",
    "Johan wennerström",
    "John",
    "John Adams",
    "John Beland",
    "John Caylor",
    "John D Aulbu",
    "John Hoskin",
    "John Martin",
    "John Weeast",
    "John smith",
    "Jon Noland",
    "Jon Waalewyn",
    "Jonathan Devore Scales",
    "Jonathon Finlay",
    "Joseph Lowery",
    "Josh Silvia",
    "Joshua Allen",
    "Joshua Sawyer",
    "Joshua Stevens",
    "José Carlos Pérez Carreño",
    "Junior Rodriguez",
    "Justin Robertson",
    "Justin Shaffner",
    "K",
    "K",
    "KJ",
    "KURT MOSS",
    "Kal basra",
    "Karl gregory",
    "Karoldue ",
    "Keith Fults",
    "Keith Kelly",
    "Kelly Morehead",
    "Kemal Tolun",
    "Ken McCune",
    "Kenny Pritchard",
    "Kevin Fellion",
    "Kevin Hare",
    "Kevin Ibrahim",
    "Kevin Kuijer",
    "Khaled W AlSulaiti",
    "Khoa Truong",
    "Kickn Chickn",
    "Kiel Arenas",
    "Klaus Dobrzynski",
    "Kourosh Vosough",
    "Kozzen",
    "Kristopher Bowling",
    "Kyle Francis",
    "Lara Marcattili",
    "Larry Hook",
    "Lars Wingemark",
    "Laura A Clegg",
    "Laura Sieloff",
    "Laurie Holmes",
    "Leeloo",
    "Leprona",
    "LivinOnTheCorner",
    "Lori Nincehelser",
    "Luca Migliorini",
    "Lucianne Dickens",
    "Luckrider",
    "Luis Flores",
    "Luke Beals",
    "Luke Newland",
    "Luke Westra",
    "MVP",
    "Macroholic",
    "Madgar29 ",
    "Magnerian",
    "Mals",
    "Manuel Nordmeier",
    "Marc allen",
    "Marcel Spieard",
    "Marcus Andesson",
    "Mardy Stevens",
    "Marek Dvořák",
    "Mark",
    "Mark ",
    "Mark Bradley",
    "Mark David McCoy 34",
    "Mark Gomersbach",
    "Mark Robinson",
    "Mark van de Beek",
    "Marshmellow",
    "Martin Needham",
    "Martin Needham",
    "Martin Vines",
    "Mathias Bohman",
    "Mathusala",
    "Matt Barile",
    "Matt Surratt",
    "Mauro colombo",
    "McLeod Turner",
    "Melchy",
    "Melissa N Anderson",
    "Melissa condon",
    "Meph",
    "Mephchens",
    "Mephiroth",
    "Mercurio",
    "Michael",
    "Michael ",
    "Michael Bailey",
    "Michael Bray",
    "Michael Brodie",
    "Michael H",
    "Michael Irving",
    "Michael Lewis",
    "Michael Mcdaniels",
    "Michael Phillips",
    "Michael R Kauffmann",
    "Michael Schulz",
    "Michael Swancott",
    "Michael W",
    "Michal Stalanowski",
    "Miethos",
    "Mike",
    "Mike Pegg",
    "Mikkel Juul Jørgensen",
    "Misty Jinn",
    "Mitchell Emberson",
    "MolarMacros",
    "Moremore Monmon",
    "Moritz Neubert",
    "MrDarque",
    "Murat",
    "Murray Technician",
    "Mystik",
    "Naomi McMillan",
    "Nathan Jetson",
    "Nathan Warfield",
    "Nawaf Aljudaibi",
    "Nebiros",
    "Neil Blain",
    "Neil C",
    "Nichola Richardson",
    "Nicholas Brown",
    "Nimmerland Gaming [NlG] Brainz",
    "Noneya Biz",
    "Nora Kirschling",
    "NotSure SureNot",
    "Obi",
    "Offline",
    "Oliver Berger",
    "Orion8 Junk",
    "Ourax",
    "Ouya France",
    "Ozzi",
    "PansaJones",
    "Patrick Lüke",
    "Patrick O'Hagan",
    "Paul Guertin",
    "Paul Harris",
    "Paul Kingman",
    "Pedro Machado Creste",
    "Penny2",
    "Peter Hansen",
    "Peter Haugen",
    "Peter McNinch",
    "Peter von der Ahe",
    "Petter Zweidorff",
    "Phat Le",
    "Phil ",
    "Pippa Martel",
    "Possum Jenkins",
    "ProWater",
    "Pwntatochip",
    "RACHEL liperote",
    "Radioactive Bullfrog",
    "Rakuza yoknomu",
    "Randall Crank",
    "Randy Barton",
    "Randy G",
    "Randy Rushing",
    "Ravn Maniac",
    "Ray Adams",
    "Ray Feliciano",
    "Raymond Monk",
    "Razerwing",
    "Rebecca Gosdin",
    "Renato Freitas",
    "Rene Traue",
    "Rhaina",
    "Richard Sears",
    "Rickey C",
    "Ricky Woods",
    "Riki Knight",
    "Robert Andersson",
    "Robert Costello",
    "Robert Ellsworth",
    "Robert Harris",
    "Robert J MacLeod",
    "Robert MacLeod",
    "Robert Mcknight",
    "Robert Pipan",
    "Robert Wears",
    "Robert Webb",
    "Robertas Suminskas",
    "Roberto Roeschmann",
    "Roberto Zanini",
    "Robin Laubinger",
    "Rodrigo Maria Soares",
    "Rodrigo Mendoza",
    "Rody z",
    "Roger Heiniluoma",
    "Rolandas Normanas",
    "RoleClass ",
    "Ronald De Martines",
    "Ronnie Otterborg",
    "Ronny Sæle",
    "Russell Baker",
    "Russell Lee Laymance",
    "Ryan ",
    "Ryan Hickey",
    "Ryan Roberts",
    "Ryo",
    "S Driggers",
    "Samma",
    "Samuel Lacerda",
    "Samuel Spencer",
    "Sandra Primm",
    "Sandy (AKA SassyGamer)",
    "Sara Bort",
    "Scarlett Knight",
    "ScaryLarryGames",
    "Schiwouna Schi",
    "Scott Davis",
    "Scott Flippo",
    "Scott Hounsell",
    "Scott Penney",
    "Scott Rose",
    "Scott Tuman",
    "Scotty",
    "Sean-Heidi Serraguard",
    "Sebastian Kieback",
    "Sergey Droba",
    "ShadyLucifer ",
    "Shane Dolby",
    "Shane Kuchler",
    "Shaun Baxter",
    "Shaun Flagel",
    "Shelltoekicks",
    "Short",
    "Shtev",
    "Sid Robichaud",
    "Sillk",
    "Simon Karlskov",
    "Simon Wilcock",
    "Sol LeTaire",
    "Solltex ",
    "Sparrowhawk Sr",
    "Spencer Blomquist",
    "Stefan Hauck",
    "Stefano Filardo",
    "Stephen Seagrave",
    "Sternwind",
    "Steve Clink",
    "Steve Hensch",
    "Steven Hansen",
    "Steven Shaw",
    "Steven Short",
    "Steven funnell",
    "Stew Frei",
    "Stormy",
    "Stuart Hendrie",
    "Supbear ",
    "Susan Mushill",
    "Susan Mushill",
    "Sven Sieber",
    "Sydney",
    "Sylvok Wolfrun",
    "T D",
    "Tabby Post",
    "Tad Oleson",
    "Tamara C Duncan ",
    "Tamer Baes",
    "Tawaporah",
    "Terry Musser",
    "The world through my eyes",
    "Thomas Maurdal",
    "Thomas Nicholson",
    "Thomas Rambaut",
    "Thore Kvalheim",
    "Thorn the Fox",
    "Tiegars",
    "Tim Firth",
    "Tim Mentink",
    "Tim Weiden",
    "Timothy Campbell",
    "Timothy allen patterson",
    "Tituswolfe",
    "Tobias Korn",
    "Tom Straugh",
    "Tommy ",
    "Tommy Southam",
    "Tommy White",
    "Topcat357",
    "Tor Ove",
    "Torbjörn Jönsson",
    "Toril Harink ",
    "Toto Leo",
    "Toxic",
    "Tracy Howard",
    "Travis ",
    "Travis Delaney",
    "Travis Watson",
    "Trevor Gordon",
    "Trevor Harper",
    "Tris",
    "Troy Rooker",
    "Truzedo ",
    "Tsaiko",
    "TwistedSMF ",
    "TwiztidBloom",
    "UhohOreo ",
    "Valamar",
    "Venni Liimatainen",
    "Victor Hodges",
    "Vince G",
    "Vince Orlando",
    "Vuudi",
    "W Wilson",
    "Walter Beiter",
    "Warren Jumper",
    "Waselbein",
    "William Kelley",
    "William Lee",
    "William P Grady",
    "William Sharp",
    "William Smith",
    "Willy",
    "Windfey",
    "Wizard Hayden",
    "Woo Kim",
    "Xingudi",
    "ZaffronStaghelm",
    "Zane Savage",
    "Zoonets",
    "Zu#4997",
    "adam humphreys",
    "alan coutts",
    "ale diki",
    "ali mohammadi",
    "andy le",
    "antonym29@gmail.com",
    "beat theory",
    "bk",
    "blastingweevil",
    "chris gallogly",
    "chris ogle",
    "cloutyTV ",
    "crystaltech",
    "curtis buffum",
    "dadbod",
    "david hawke",
    "devlik",
    "dixon garyck",
    "eren ",
    "evasion",
    "ffcjonny",
    "friedbones",
    "garrett ainsworth",
    "giorgino",
    "impaxx ",
    "james hyatt",
    "james stuart broderick",
    "jamie bradley",
    "jay garcia",
    "jean-marie rossi",
    "joe faultless",
    "kay rennow",
    "kelly jarrell",
    "kristian montevecchi",
    "levend62",
    "lloyd spencer",
    "luc janssens",
    "manuel Leistner",
    "mika ai",
    "mike sano",
    "mike saul",
    "mourad abrahim",
    "mr mods",
    "neofodder",
    "nistule",
    "pantinhatv",
    "pascalmaramis",
    "patrice heinemann",
    "paytun",
    "quoc nguyen",
    "rachid benchaou",
    "ralf heckel",
    "rightonetwo",
    "ryan kloepper",
    "stagd ",
    "sten",
    "stiph curry",
    "thebadcatbot.com",
    "todd greaves",
    "ttplank",
    "twmwalters",
    "wouZAR ",
    "wynne clark",
    "xManiac",
    "xan2622",
    "zibiken",
    "Александр Кузьмин",
    "مشعل العنزي",
    "熙 凌"
}