if GetLocale() ~= "frFR" then
    return
end

local L = LibStub("AceLocale-3.0"):NewLocale("GSE", "frFR")

-- Options translation
L["  The Alternative ClassID is "] = " La ClassID alternative est "
L[" Deleted Orphaned Macro "] = "Macro orpheline supprimée"
L[" from "] = "de"
L[" has been added as a new version and set to active.  Please review if this is as expected."] = "a été ajouté comme nouvelle version et a été activé. Veuillez vérifier si cela vous convient."
L[" is not available.  Unable to translate sequence "] = "n'est pas disponible. Impossible de traduire la macro"
L[" macros per Account.  You currently have "] = "macros par compte. Vous en avez actuellement"
L[" macros per character.  You currently have "] = "macros par personnage. Vous en avez actuellement"
L[" saved as version "] = "enregistré sous la version"
L[" sent"] = "envoyé"
L[" tried to overwrite the version already loaded from "] = "a essayé d'écraser la version déjà chargée depuis"
L[" was imported as a new macro."] = "a été importé comme une nouvelle macro."
L[" was imported with the following errors."] = "a été importé avec les erreurs suivantes."
L[" was updated to new version."] = " a été mis à jour sous une nouvelle version."
L["%s macro may cause a 'RestrictedExecution.lua:431' error as it has %s actions when compiled.  This get interesting when you go past 255 actions.  You may need to simplify this macro."] = "La macro %s peut provoquer une erreur 'RestrictedExecution.lua:431' car elle contient des actions %s lors de la compilation. Cela devient intéressant lorsque vous dépassez 255 actions. Vous devrez peut-être simplifier cette macro."
L["%sMACRO VALIDATION ERROR|r - PostMacro found with invalid LoopLimit.  PostMacro will not be saved for version %s"] = "%sERREUR DE VALIDATION MACRO|r - Une Boucle Intérieure (LoopLimit) invalide a été trouvée dans PostMacro. PostMacro ne sera pas enregistré en version %s"
L[". This version was not loaded."] = ". Cette version n'a pas été chargée."
L["/gse checkmacrosforerrors|r will loop through your macros and check for corrupt macro versions.  This will then show how to correct these issues."] = "/gse checkmacrosforerrors|r parcourra vos macros et vérifiera les versions de macro corrompues. Cela vous montrera ensuite comment corriger ces problèmes."
L["/gse cleanorphans|r will loop through your macros and delete any left over GSE macros that no longer have a sequence to match them."] = "/gse cleanorphans|r parcourra vos macros et supprimera toutes les macros GSE restantes qui n'ont plus de séquence qui leur corresponde."
L["/gse help|r to get started."] = "Tapez /gse help|r pour commencer."
L["/gse showspec|r will show your current Specialisation and the SPECID needed to tag any existing macros."] = "/gse showspec|r affichera votre spécialisation actuelle et le SPECID nécessaire pour taguer toutes les macros existantes."
--[[Translation missing --]]
L["/gse|r again."] = "/gse|r again."
L["/gse|r to get started."] = "Tapez gse|r pour commencer."
L["/gse|r will list any macros available to your spec.  This will also add any macros available for your current spec to the macro interface."] = "/gse|r listera toutes les macros disponibles pour votre spécification. Cela ajoutera également toutes les macros disponibles pour votre spécification actuelle à l'interface des macros."
L[":|r To get started "] = ":|r Pour commencer"
L[":|r You cannot delete the only copy of a sequence."] = ":|r vous ne pouvez pas supprimer l'unique copie de la macro."
L[":|r Your current Specialisation is "] = ":|r Votre spécialisation actuelle est"
L["|r Incomplete Sequence Definition - This sequence has no further information "] = "|r Définition de la macro incomplète - Cette macro n'a pas d'autres informations"
L["|r.  As a result this macro was not created.  Please delete some macros and reenter "] = "|r. Par conséquent, cette macro n'a pas été créée. Veuillez supprimer quelques macros et entrer à nouveau"
L["|r.  You can also have a  maximum of "] = "|r. Vous pouvez également avoir un maximum de "
L["<DEBUG> |r "] = "<DEBUG> |r"
L["<SEQUENCEDEBUG> |r "] = "<SEQUENCEDEBUG> |r"
L[ [=[A pause can be measured in either clicks or seconds.  It will either wait 5 clicks or 1.5 seconds.
If using seconds, you can also wait for the GCD by entering ~~GCD~~ into the box.]=] ] = "Une pause peut être mesurée en clics ou en secondes. Ca attendra 5 clics ou 1,5 seconde. Si vous utilisez des secondes, vous pouvez également attendre le GCD en entrant ~~GCD~~ ."
L["A sequence collision has occured. "] = "Un conflit entre plusieurs macros s'est produit."
L["A sequence collision has occured.  Extra versions of this macro have been loaded.  Manage the sequence to determine how to use them "] = "Un conflit entre plusieurs macros s'est produit. Des versions supplémentaires de cette macro ont été chargées. Vérifiez la macro pour déterminer comment utiliser ces versions"
L["A sequence collision has occured.  Your local version of "] = "Un conflit entre macros s'est produit. Votre version locale de"
L["About"] = "A propos "
L["About GSE"] = "A propos de GSE"
--[[Translation missing --]]
L["ActionButtonUseKeyDown"] = "ActionButtonUseKeyDown"
L["Actions"] = "Actions"
L["Active Version: "] = "Version active :"
L["Add a Loop Block."] = "Ajoute un bloc pour la boucle."
L["Add a Pause Block."] = "Ajoute un bloc pour la pause."
L["Add a Repeat Block."] = "Ajoute un bloc pour la répétition."
L["Add a substitution variable for this macro.  This can either be a straight string swap or can be a function.  If a lua function the function needs to return a value."] = "Ajoutez une variable de substitution pour cette macro. Vous pouvez soit directement changer la ligne, soit une fonction. S'il s'agit d'une fonction lua, la fonction doit renvoyer une valeur. "
L["Add Action"] = "Ajouter une action"
L["Add an Action Block."] = "Ajoute un bloc pour l'action."
L["Add an If Block.  If Blocks allow you to shoose between blocks based on the result of a variable that returns a true or false value."] = "Ajoute un bloc Si. Les blocs Si vous permettent de choisir entre différents blocs en fonction du résultat d'une variable qui renvoie une valeur vraie ou fausse."
L["Add If"] = "Ajouter un bloc Si"
L["Add Loop"] = "Ajouter une boucle"
L["Add Pause"] = "Ajouter une pause"
L["Add Repeat"] = "Ajouter une répétition"
L["Add Variable"] = "Ajouter une variable"
L["Add WeakAura"] = "Ajouter un WeakAura"
L["Addin Version %s contained versions for the following macros:"] = "%s est une variable qui sera remplacée à l'exécution par un nom de macro. Ne pas y toucher."
L["All macros are now stored as upper case names.  You may need to re-add your old macros to your action bars."] = "Toutes les macros sont désormais stockées sous forme de noms en majuscules. Vous devrez peut-être rajouter vos anciennes macros à vos barres d'action."
L["Alt Keys."] = "Touches Alt"
--[[Translation missing --]]
L["Alwaus use the highest rank of spell available.  This is useful for levelling."] = "Alwaus use the highest rank of spell available.  This is useful for levelling."
--[[Translation missing --]]
L["Always use Max Rank"] = "Always use Max Rank"
L["Any Alt Key"] = "Touche Alt gauche ou droite"
L["Any Control Key"] = "Touche Ctrl gauche ou droite"
L["Any Shift Key"] = "Touche Maj gauche ou droite"
L["Are you sure you want to delete %s?  This will delete the macro and all versions.  This action cannot be undone."] = "Etes-vous sûr de vouloir supprimer %s ? La macro et toutes ses versions seront supprimées. Cette action ne peut pas être annulée."
L["Arena"] = "Arène"
L["Arena setting changed to Default."] = "Les paramètres des Arènes ont été définis comme ceux par défaut."
L["As GSE is updated, there may be left over macros that no longer relate to sequences.  This will check for these automatically on logout.  Alternatively this check can be run via /gse cleanorphans"] = "Au fur et à mesure que GSE est mis à jour, il peut rester des macros qui ne sont plus liées aux séquences. Ceci les vérifiera automatiquement à la déconnexion. Sinon, cette vérification peut être exécutée via /gse cleanorphans"
L["Auras included in GSE Macros"] = "Auras inclues dans les macros GSE"
L["Author"] = "Auteur"
L["Author Colour"] = "Couleur de l'auteur"
L["Auto Create Class Macro Stubs"] = "Créer les emplacements de macros de classe automatiquement"
L["Auto Create Global Macro Stubs"] = "Créer les emplacements de macros globales automatiquement"
L["Automatically Create Macro Icon"] = "Créer automatiquement l'icône de la macro"
L["Available Addons"] = "Addons disponibles"
L["Belt"] = "Ceinture"
L["Blizzard Functions Colour"] = "Couleur des fonctionnalités Blizzard"
--[[Translation missing --]]
L["Block Path"] = "Block Path"
L["Block Type: %s"] = "Type de bloc : %s"
L["Boolean Functions"] = "Fonctions booléennes"
L["Boolean Functions are GSE variables that return either a true or false value."] = "Les fonctions booléennes sont des variables GSE qui renvoient une valeur vraie ou fausse."
L["Boolean not found.  There is a problem with %s not returning true or false."] = "Booléen introuvable. Il y a un problème avec %s qui ne renvoie pas vrai ou faux."
L["By setting the default Icon for all macros to be the QuestionMark, the macro button on your toolbar will change every key hit."] = [=[Cette option ajoutera l'icône par défaut (le point d'interrogation) à toutes vos macros. Ainsi, le bouton de votre macro (sur votre barre d'outils) changera à chaque frappe de touche en affichant l'îcone de chaque sort.
]=]
L["By setting this value the Sequence Editor will show every macro for every class."] = "Si coché, l'Editeur de Macro affichera toutes les macros de toutes les classes."
L["By setting this value the Sequence Editor will show every macro for your class.  Turning this off will only show the class macros for your current specialisation."] = "Si coché, l'Editeur de Macro affichera toutes les macros pour votre classe. Désactiver cette option pour n'afficher que les macros pour votre spécialisation actuelle."
L["Cancel"] = "Annuler"
L["Character"] = "Personnage"
L["Character Specific Options which override the normal account settings."] = "Options spécifiques aux personnages qui remplacent les paramètres normaux du compte."
L["CheckMacroCreated"] = "Vérifiez la macro créée"
L["Checks to see if you have a Heart of Azeroth equipped and if so will insert '/cast Heart Essence' into the macro.  If not your macro will skip this line."] = "Vérifie si vous êtes équipé d'un Cœur d'Azeroth et si c'est le cas, insère '/cast Heart Essence' dans la macro. Sinon, votre macro sautera cette ligne."
L["Choose import action:"] = "Choisissez comment importer :"
L["Choose Language"] = "Choisissez votre langue"
L["Classwide Macro"] = "Macro de classe"
L["Clear"] = "Effacer"
L["Clear Common Keybindings"] = "Effacer les raccourcis clavier principaux"
L["Clear Errors"] = "Effacer les erreurs"
L["Clear Keybindings"] = "Effacer les raccourcis clavier"
--[[Translation missing --]]
L["Clear Spell Cache"] = "Clear Spell Cache"
L["Clicks"] = "Clics"
L["Close"] = "Fermer"
L["Close to Maximum Macros.|r  You can have a maximum of "] = "Nombre de macros presque atteint.|r Vous pouvez avoir un maximum de"
L["Close to Maximum Personal Macros.|r  You can have a maximum of "] = "Nombre de macros pour ce perso presque atteint.|r Vous pouvez avoir un maximum de"
L["Colour"] = "Couleur"
L["Colour and Accessibility Options"] = "Couleur et options d'accessibilité"
L["Combat"] = "Combat"
L["Command Colour"] = "Couleur des commandes"
--[[Translation missing --]]
L["Common Solutions to game quirks that seem to affect some people."] = "Common Solutions to game quirks that seem to affect some people."
L["Compile"] = "Compiler"
L["Compiled"] = "Compilé"
L["Compiled Template"] = "Version compilée"
L["Completely New GS Macro."] = "Nouvelle macro GSE vierge."
L["Compress"] = "Compresser"
L["Compress Sequence from Forums"] = "Compresser les macros provenant de forums"
L["Conditionals Colour"] = "Couleur des conditions"
L["Configuration"] = "Configuration"
L["Continue"] = "Continuer"
L["Contributed by: "] = "Contribution de :"
L["Control Keys."] = "Touches Ctrl"
--[[Translation missing --]]
L["Convert"] = "Convert"
--[[Translation missing --]]
L["Convert this to a GSE3 Template"] = "Convert this to a GSE3 Template"
L["Copy this link and open it in a Browser."] = "Copiez ce lien et ouvrez-le dans un navigateur."
L["Copy this link and paste it into a chat window."] = "Copiez ce lien et collez-le dans une fenêtre de discussion."
L["Create a new macro."] = "Créer une nouvelle macro."
L["Create buttons for Global Macros"] = "Créer des boutons pour les Macros Gobales"
L["Create Icon"] = "Créer l'icône"
L["Create Macro"] = "Créer la macro"
L[ [=[Create or remove a Macro stub in /macro that can be dragged to your action bar so that you can use this macro.
GSE can store an unlimited number of macros however WOW's /macro interface can only store a limited number of macros.]=] ] = "Créez ou supprimez un emplacement de macro dans /macro qui peut être glissé vers votre barre d'action afin que vous puissiez utiliser cette macro. \\nGSE peut stocker un nombre illimité de macros, mais l'interface /macro de WOW ne peut stocker qu'un nombre limité de macros."
L["Creating New Sequence."] = "Création d'une nouvelle macro."
L["Current GCD"] = "CGD actuel"
L["Current GCD: %s"] = "GCD actuel : %s"
--[[Translation missing --]]
L["CVar Settings"] = "CVar Settings"
L["Debug"] = "Débogage"
L["Debug Mode Options"] = "Options du mode de débogage"
L["Debug Output Options"] = "Options de sortie de débogage"
L["Debug Sequence Execution"] = "Exécution du débogage de la macro"
L["Decompress"] = "Décompresser"
L["Default Debugger Height"] = "Hauteur par défaut du débogueur"
L["Default Debugger Width"] = "Largeur par défaut du débogueur"
L["Default Editor Height"] = "Hauteur par défaut de l'éditeur"
L["Default Editor Width"] = "Largeur par défaut de l'éditeur"
L["Default Import Action"] = "Action d'importation par défaut"
L["Default Menu Height"] = "Hauteur par défaut de la liste"
L["Default Menu Width"] = "Largeur par défaut de la liste"
L["Default Version"] = "Version par défaut"
L["Del"] = "Suppr"
L["Delete"] = "Supprimer"
L["Delete Block"] = "Supprimer le bloc"
L["Delete Icon"] = "Supprimer l'icône"
L["Delete Orphaned Macros on Logout"] = "Supprimer les macros orphelines à la déconnexion du jeu"
L[ [=[Delete this Block from the sequence.  
WARNING: If this is a loop this will delete all the blocks inside the loop as well.]=] ] = "Supprimer ce bloc de la séquence. AVERTISSEMENT : S'il s'agit d'une boucle, tous les blocs à l'intérieur de la boucle seront également supprimés."
L["Delete this macro.  This is not able to be undone."] = "Supprimer cette macro. Cette action est irréversible."
L["Delete this variable from the sequence."] = "Supprime cette variable de la macro."
L[ [=[Delete this verion of the macro.  This can be undone by closing this window and not saving the change.  
This is different to the Delete button below which will delete this entire macro.]=] ] = "Supprime uniquement cette version de la macro. Cette action peut être annulée en fermant cette fenêtre et en n'enregistrant pas les modifications. \\nCette action n'entraine pas la suppression de toute la macro (contrairement au bouton Supprimer ci-dessous qui lui la supprime entièrement). "
L["Delete this WeakAura from the sequence."] = "Supprime ce WeakAura de la macro. "
L["Delete Variable"] = "Supprimer la variable"
L["Delete Version"] = "Supprimer cette version"
L["Delete WeakAura"] = "Supprimer WeakAura"
L["Different helpTxt"] = "helpTxt est différent"
L["Disable"] = "Désactiver"
L["Disable Block"] = "Désactiver ce bloc"
L["Disable Editor"] = "Désactiver l'éditeur"
L["Disable Sequence"] = "Désactiver la macro"
L["Disable this block so that it is not executed. If this is a container block, like a loop, all the blocks within it will also be disabled."] = "Désactiver ce bloc pour qu'il ne soit pas exécuté. S'il s'agit d'un bloc conteneur, comme une boucle, tous les blocs qu'il contient seront également désactivés."
L["Display debug messages in Chat Window"] = "Afficher les messages de débogage dans la fenêtre de discussion"
--[[Translation missing --]]
L["Don't Force"] = "Don't Force"
L["Don't Translate Sequences"] = "Ne pas traduire les macros"
L["Drag this icon to your action bar to use this macro. You can change this icon in the /macro window."] = "Faites glisser cette icône sur votre barre d'action pour utiliser cette macro. Vous pouvez changer l'icône dans la fenêtre /macro."
--[[Translation missing --]]
L["Dragonflight has changed how the /click command operates.  As a result all your macro stubs (found in /macro) have been updated to match the value of the CVar ActionButtonUseKeyDown.  This is a one off configuration change that needs to be done for each character.  You can change this configuration in GSE's Options."] = "Dragonflight has changed how the /click command operates.  As a result all your macro stubs (found in /macro) have been updated to match the value of the CVar ActionButtonUseKeyDown.  This is a one off configuration change that needs to be done for each character.  You can change this configuration in GSE's Options."
L["Dungeon"] = "Donjon"
L["Dungeon setting changed to Default."] = "Les paramètres des Donjons ont été définis comme ceux par défaut."
L["Edit"] = "Modifier"
--[[Translation missing --]]
L["Edit Spell Cache"] = "Edit Spell Cache"
L["Edit this macro directly in Lua. WARNING: This may render the macro unable to operate and can crash your Game Session."] = "Modifiez cette macro directement en language Lua. AVERTISSEMENT : cela peut rendre la macro incapable de fonctionner et faire planter votre session de jeu."
L["Edit this macro.  To delete a macro, choose this edit option and then from inside hit the delete button."] = "Modifie cette macro. Pour supprimer une macro, choisissez \"Modifier\", puis dans la fenêtre qui apparaît, appuyez sur le bouton \"Supprimer\"."
L["Editor Colours"] = "Couleurs de l'éditeur"
L["Emphasis Colour"] = "Couleur d'emphase"
L["Enable"] = "Activer"
L["Enable Debug for the following Modules"] = "Activer le débogage pour les modules suivants"
L["Enable Mod Debug Mode"] = "Activer le mode de débogage"
L["Enable Sequence"] = "Activer la macro"
L["Enable this option to stop automatically translating sequences from enUS to local language."] = "Activez cette option pour arrêter la traduction automatique des macros en langue anglaise (enUS) vers la langue locale (frFR)."
L["Enable timing functions by using Click refresh speed as a pseudo timer."] = "Utilise la vitesse de rafraîchissement du clic."
L["Enforce GSE minimum version for this macro"] = "Impose une version minimale de GSE pour cette macro"
L["Error found in version %i of %s."] = "Erreur trouvée dans la version %i de %s."
L["Error processing Custom Pause Value.  You will need to recheck your macros."] = "Erreur lors du traitement de la pause personnalisée. Vous devrez revérifier vos macros."
--[[Translation missing --]]
L["Error: Destination path not found."] = "Error: Destination path not found."
--[[Translation missing --]]
L["Error: Source path not found."] = "Error: Source path not found."
--[[Translation missing --]]
L["Error: You cannot move a container to be a child within itself."] = "Error: You cannot move a container to be a child within itself."
L["Export"] = "Exporter"
L["Export a Sequence"] = "Exporter une macro"
L["Export Macro Read Only"] = "Exporter la macro en lecture seule"
L["Export this Macro."] = "Exporter cette macro."
L["Extra Macro Versions of %s has been added."] = "Des versions de macro supplémentaires de %s ont été ajoutées."
L["Filter Macro Selection"] = "Filtrer la sélection de macros"
L["Finished scanning for errors.  If no other messages then no errors were found."] = "Recherche d'erreurs terminée. S'il n'y a pas d'autres messages, alors aucune erreur n'a été trouvée. "
L["FinishReload"] = "Finish Reload"
L["Fix SetBackdrop Nil"] = "Fix SetBackdrop Nil"
--[[Translation missing --]]
L["Force ActionButtonUseKeyDown State"] = "Force ActionButtonUseKeyDown State"
--[[Translation missing --]]
L["Force CVar State"] = "Force CVar State"
L["Format export for WLM Forums"] = "Exporter au format WLM pour les forums"
L["FYou cannot delete this version of a sequence.  This version will be reloaded as it is contained in "] = "Vous ne pouvez pas supprimer cette version de la macro. Cette version sera rechargée telle qu'elle est contenue dans"
L["Gameplay Options"] = "Options de jeu"
L["General"] = "Général"
L["General Options"] = "Options générales"
L["Get Help"] = "Demander de l'aide"
L["Global"] = "Global"
L["Global Macros are those that are valid for all classes.  GSE2 also imports unknown macros as Global.  This option will create a button for these macros so they can be called for any class.  Having all macros in this space is a performance loss hence having them saved with a the right specialisation is important."] = "Les macros globales sont celles qui sont valables pour toutes les classes. GSE importe également des macros \"inconnues\" en tant que Global. Cette option crée un bouton pour ces macros afin qu'elles puissent être lancées par n'importe quelle classe. Avoir toutes les macros dans cet espace est une perte de performances, il est donc important de les enregistrer avec la bonne spécialisation."
L["Gnome Sequencer: Compress a Sequence String."] = "Gnome Sequencer : Compression d'une partie de macro"
L["Gnome Sequencer: Export a Sequence String."] = "Gnome Sequencer : Exportation d'une partie de macro"
L["Gnome Sequencer: Record your rotation to a macro."] = "Gnome Sequencer : enregistrez votre rotation dans une macro."
L["Gnome Sequencer: Sequence Debugger. Monitor the Execution of your Macro"] = "Gnome Sequencer: Débogueur de Macro. Permet de suivre l'exécution de votre macro."
L["Gnome Sequencer: Sequence Editor."] = "Gnome Sequencer : Editeur de Macro"
L["GnomeSequencer was originally written by semlar of wowinterface.com."] = "GnomeSequencer a été initialement écrit par semlar de wowinterface.com."
L["GnomeSequencer-Enhanced"] = "Gnome Sequencer Enhanced"
L["GSE"] = "GSE"
L["GSE - %s's Macros"] = "GSE - Macros de %s"
L["GSE allows plugins to load Macro Collections as plugins.  You can reload a collection by pressing the button below."] = "GSE permet à des plugins de charger des \"collections de macros\" en tant que plugins. Vous pouvez recharger une collection en appuyant sur le bouton ci-dessous."
L["GSE has a LibDataBroker (LDB) data feed.  List Other GSE Users and their version when in a group on the tooltip to this feed."] = "GSE dispose d'un flux de données LibDataBroker (LDB). Cochez cette case pour afficher dans l'info-bulle les autres utilisateurs de GSE ainsi que leur version de GSE lorsqu'ils sont dans un groupe."
L["GSE has a LibDataBroker (LDB) data feed.  Set this option to show queued Out of Combat events in the tooltip."] = "GSE dispose d'un flux de données LibDataBroker (LDB). Cochez cette case pour afficher les événements hors combat en file d'attente dans l'info-bulle."
L["GSE is a complete rewrite of that addon that allows you create a sequence of macros to be executed at the push of a button."] = "GSE est basé sur cet addon mais a été complètement réécrit pour vous permettre de créer une suite de macros à exécuter en appuyant successivement sur un bouton."
L["GSE is out of date. You can download the newest version from https://www.curseforge.com/wow/addons/gse-gnome-sequencer-enhanced-advanced-macros."] = "GSE est obsolète. Vous pouvez télécharger la dernière version sur https://www.curseforge.com/wow/addons/gse-gnome-sequencer-enhanced-advanced-macros ."
L["GSE Macro"] = "Macro GSE"
--[[Translation missing --]]
L["GSE Macro Stubs have been reset to KeyDown configuration.  The /click command needs to be `/click TEMPLATENAME LeftButton t` (Note the 't' here is required along with the LeftButton.)"] = "GSE Macro Stubs have been reset to KeyDown configuration.  The /click command needs to be `/click TEMPLATENAME LeftButton t` (Note the 't' here is required along with the LeftButton.)"
--[[Translation missing --]]
L["GSE Macro Stubs have been reset to KeyUp configuration.  The /click command needs to be `/click TEMPLATENAME`"] = "GSE Macro Stubs have been reset to KeyUp configuration.  The /click command needs to be `/click TEMPLATENAME`"
L["GSE Plugins"] = "Plugins GSE"
L["GSE Raw Editor"] = "GSE Editeur brut"
L["GSE stores the base spell and asks WoW to use that ability.  WoW will then choose the current version of the spell.  This toggle switches between showing the Base Spell or the Current Spell."] = "GSE stocke le sort de base et demande à WoW d'utiliser cette compétence. WoW choisira alors la version actuelle du sort. Cela permet de basculer entre l'affichage du sort de base ou du sort actuel."
L["GSE Users"] = "Utilisateurs GSE"
L["GSE Version: %s"] = "La version de GSE est la %s"
L[ [=[GSE was originally forked from GnomeSequencer written by semlar.  It was enhanced by TImothyLuke to include a lot of configuration and boilerplate functionality with a GUI added.  The enhancements pushed the limits of what the original code could handle and was rewritten from scratch into GSE.

GSE itself wouldn't be what it is without the efforts of the people who write macros with it.  Check out https://wowlazymacros.com for the things that make this mod work.  Special thanks to Lutechi for creating this community.]=] ] = "GSE est un addon initialement basé sur GnomeSequencer, écrit par semlar. GSE a ensuite été amélioré par TimothyLuke en ajoutant de nombreuses fonctionnalités de configuration ainsi qu'une interface graphique. Il a ensuite été réécrit à partir de zéro pour permettre de faciliter son futur développement. GSE lui-même ne serait pas ce qu'il est sans les personnes qui créent des macros avec. Consultez https://wowlazymacros.com pour savoir comment fonctionne cet addon. Un merci spécial à Lutechi pour la création de cette communauté."
L["GSE: Advanced Macro Compiler loaded.|r  Type "] = "GSE: Advanced Macro Compiler chargé.|r Type"
L["GSE: Import a Macro String."] = "GSE : Importation d'une macro (ou d'une partie de celle-ci)"
L["GSE: Left Click to open the Sequence Editor"] = "GSE : Clic gauche pour ouvrir l'Editeur de Macro"
L["GSE: Middle Click to open the Transmission Interface"] = "GSE : Clic central de la souris pour ouvrir l'interface de transmission"
L["GSE: Right Click to open the Sequence Debugger"] = "GSE : Clic droit pour ouvrir le Débogueur de Macro"
--[[Translation missing --]]
L["GSE2 Retro Importer available."] = "GSE2 Retro Importer available."
--[[Translation missing --]]
L["GSE2 Retro interface loaded.  Type `%s/gse2 import%s` to import an old GSE2 string or `%s/gse2 edit%s` to mock up a new template using the GSE2 editor."] = "GSE2 Retro interface loaded.  Type `%s/gse2 import%s` to import an old GSE2 string or `%s/gse2 edit%s` to mock up a new template using the GSE2 editor."
--[[Translation missing --]]
L["GSE2 Retro:"] = "GSE2 Retro:"
L["Head"] = "Tête"
L["Help Colour"] = "Couleur pour l'aide"
L["Help Information"] = "Informations"
L["Help Link"] = "Lien"
L["Help URL"] = "URL d'aide"
L["Heroic"] = "Héroïque"
L["Heroic setting changed to Default."] = "Les paramètres des Héroïques ont été définis comme ceux par défaut."
L["Hide Login Message"] = "Masquer le message de connexion"
L["Hide Minimap Icon"] = "Masquer l'icône de la minicarte"
L["Hide Minimap Icon for LibDataBroker (LDB) data text."] = "Cochez cette case pour masquer l'icône de la minicarte."
L["Hides the message that GSE is loaded."] = "Masque le message indiquant que GSE est chargé."
L["History"] = "Historique"
L["How many macro Clicks to pause for?"] = "Pendant combien de \"clics\" faire la pause ?"
L["How many milliseconds to pause for?"] = "Combien de millisecondes faut-il faire une pause ?"
L["How many pixels high should the Debuger start at.  Defaults to 500"] = "A quelle dimension (hauteur) le débogueur doit-il démarrer. Par défaut à 500 pixels."
L["How many pixels high should the Editor start at.  Defaults to 700"] = "Hauteur minimale pour l'éditeur. La valeur par défaut est 700 pixels. "
L["How many pixels high should the Menu start at.  Defaults to 500"] = "A quelle dimension (hauteur) la liste doit-elle démarrer. Par défaut à 500 pixels."
L["How many pixels wide should the Debugger start at.  Defaults to 700"] = "A quelle dimension (largeur) le débogueur doit-il démarrer. Par défaut à 700 pixels."
L["How many pixels wide should the Editor start at.  Defaults to 700"] = "Largeur minimale pour l'éditeur. La valeur par défaut est 700 pixels. "
L["How many pixels wide should the Menu start at.  Defaults to 700"] = "A quelle dimension (largeur) la liste doit-elle démarrer. Par défaut à 700 pixels."
L["How many seconds to pause for?"] = "Pendant combien de secondes faire la pause ?"
L["How many times does this action repeat"] = "Combien de fois cette action doit se répéter"
L["Icon Colour"] = "Couleur de l'icône"
L["If Blocks require a variable that returns either true or false.  Create the variable first."] = "Les blocs Si nécessitent une variable qui renvoie vrai ou faux. Créez d'abord la variable."
L["If Blocks Require a variable."] = "Les blocs 'SI' requièrent une variable."
L["If you load Gnome Sequencer - Enhanced and the Sequence Editor and want to create new macros from scratch, this will enable a first cut sequenced template that you can load into the editor as a starting point.  This enables a Hello World macro called Draik01.  You will need to do a /console reloadui after this for this to take effect."] = "Si vous lancez l'Editeur de Macro de GSE et que vous souhaitez créer de nouvelles macros à partir de zéro, ceci chargera un modèle de base que vous pourrez utiliser comme point de départ. Ceci active une macro Hello World appelée Draik01. Vous devrez ensuite effectuer un rechargement /console cela pour que cela prenne effet."
L["Ignore"] = "Ignorer"
L["Import"] = "Importer"
L["Import Macro from Forums"] = "Importer une macro à partir de forums."
L["Imported new sequence "] = "Nouvelle macro importée"
L["Incorporate the belt slot into the KeyRelease. This is the equivalent of /use [combat] 5 in a KeyRelease."] = "Intègre l'emplacement de ceinture dans le KeyRelease. C'est l'équivalent de /use [combat] 5 dans un KeyRelease."
L["Incorporate the first ring slot into the KeyRelease. This is the equivalent of /use [combat] 11 in a KeyRelease."] = "Intègre le premier emplacement d'anneau dans le KeyRelease. C'est l'équivalent de /use [combat] 11 dans un KeyRelease."
L["Incorporate the first trinket slot into the KeyRelease. This is the equivalent of /use [combat] 13 in a KeyRelease."] = "Intègre le premier emplacement de bijou dans le KeyRelease. C'est l'équivalent de /use [combat] 13 dans un KeyRelease."
L["Incorporate the Head slot into the KeyRelease. This is the equivalent of /use [combat] 1 in a KeyRelease."] = "Intègre l'emplacement de tête dans le KeyRelease. C'est l'équivalent de /use [combat] 1 dans un KeyRelease."
L["Incorporate the neck slot into the KeyRelease. This is the equivalent of /use [combat] 2 in a KeyRelease."] = "Intègre l'emplacement de cou dans le KeyRelease. C'est l'équivalent de /use [combat] 2 dans un KeyRelease."
L["Incorporate the second ring slot into the KeyRelease. This is the equivalent of /use [combat] 12 in a KeyRelease."] = "Intègre le second emplacement d'anneau dans le KeyRelease. C'est l'équivalent de /use [combat] 12 dans un KeyRelease."
L["Incorporate the second trinket slot into the KeyRelease. This is the equivalent of /use [combat] 14 in a KeyRelease."] = "Intègre le deuxième emplacement de bijou dans le KeyRelease. C'est l'équivalent de /use [combat] 14 dans un KeyRelease."
L["Inner Loop End"] = "Fin de Boucle Interne"
L["Inner Loop Limit"] = "Boucle Interne"
L[ [=[Inner Loop Limit controls how many times the Sequence part of your macro executes 
until it goes onto to the PostMacro and then resets to the PreMacro.]=] ] = "La \"Boucle Intérieure\" sert à indiquer à GSE combien de fois vous voulez exécuter le bloc \\n \"Séquence\" jusqu'à ce que la macro passe à \"PostMacro\", puis se réinitialise et passe à \"PreMacro\"."
L["Inner Loop Start"] = "Début de Boucle Interne"
L["Insert this block again after how many blocks."] = "Insérer à nouveau ce bloc après un nombre de blocs défini."
L["Interval"] = "Intervalle"
L["Invalid value entered into pause block. Needs to be 'GCD' or a Number."] = "Une valeur invalide a été entrée dans le bloc de pause. Ce doit être \"GCD\" ou un nombre."
--[[Translation missing --]]
L["KeyDown"] = "KeyDown"
L["KeyPress"] = "KeyPress"
L["KeyRelease"] = "KeyRelease"
--[[Translation missing --]]
L["KeyUp"] = "KeyUp"
L["Language"] = "Langue"
L["Language Colour"] = "Couleur de langue"
L["Left Alt Key"] = "Touche Alt gauche"
L["Left Control Key"] = "Touche Ctrl gauche"
L["Left Mouse Button"] = "Bouton gauche de la souris"
L["Left Shift Key"] = "Touche Maj gauche"
L["Legacy GS/GSE1 Macro"] = "Macro obsolète GS/GSE1"
L["Like a /castsequence macro, it cycles through a series of commands when the button is pushed. However, unlike castsequence, it uses macro text for the commands instead of spells, and it advances every time the button is pushed instead of stopping when it can't cast something."] = "Comme une macro /castsequence, il parcourt une série de commandes lorsque le bouton est enfoncé. Cependant, contrairement à castsequence, il utilise du texte de macro pour les commandes au lieu de sorts, et avance à chaque fois que le bouton est enfoncé au lieu de s'arrêter lorsqu'il ne peut pas lancer quelque chose."
L["Load"] = "Charger"
L["Load or update this WeakAura into WeakAuras."] = "Chargez ou mettre à jour ce WeakAura dans WeakAuras."
L["Load Sequence"] = "Charger la macro"
L["Load WeakAura"] = "Charger ce WeakAura"
L["Local Function: "] = "Fonction locale :"
L["Local Macro"] = "Macro locale"
L["Macro Collection to Import."] = "Collection de macros à importer."
L["Macro Compile Error"] = "Erreur de compilation de la macro."
L["Macro found by the name %sPVP%s. Rename this macro to a different name to be able to use it.  WOW has a global object called PVP that is referenced instead of this macro."] = "Macro trouvée sous le nom %sPVP%s. Renommez cette macro sous un autre nom pour pouvoir l'utiliser. WOW a un objet global appelé PVP qui est référencé à la place de cette macro."
L["Macro found by the name %sWW%s. Rename this macro to a different name to be able to use it.  WOW has a hidden button called WW that is executed instead of this macro."] = "Macro trouvée sous le nom %sWW%s. Renommez cette macro sous un autre nom pour pouvoir l'utiliser. WOW a un bouton caché appelé WW qui est exécuté à la place de cette macro."
L["Macro Icon"] = "Icône de la macro"
L["Macro Import Successful."] = "Importation de macro réussie."
L["Macro Reset"] = "Réinitialisation de la macro"
L["Macro unable to be imported."] = "Macro impossible à importer."
L["Macro Variables"] = "Variables de la macro"
L["Macro Version %d deleted."] = "La version %d a été supprimée."
L["Make Active"] = "Rendre actif"
L["Manage Versions"] = "Gérer les versions"
L["Matching helpTxt"] = "helpTxt correspond"
L["Measure"] = "Mesurer"
L["Merge"] = "Fusionner"
L["MergeSequence"] = "FusionDeMacro"
L["Middle Mouse Button"] = "Bouton central de la souris"
L["Millisecond click settings"] = "Paramètres des clics (en millisecondes)"
L["Milliseconds"] = "Millisecondes"
L["Mouse Button 4"] = "Bouton de la souris 4"
L["Mouse Button 5"] = "Bouton de la souris 5"
L["Mouse Buttons."] = "Buttons de la souris"
L["Move Down"] = "Descendre"
L["Move this block down one block."] = "Descend ce bloc d'un cran (un bloc en dessous)."
L["Move this block up one block."] = "Monte ce bloc d'un cran (un bloc au dessus)."
L["Move Up"] = "Monter"
L["Moved %s to class %s."] = "%s a été déplacé vers la classe %s."
L["MS Click Rate"] = "Vitesse des clics en millisecondes (ms)"
L["Mythic"] = "Mythique"
L["Mythic setting changed to Default."] = "Les paramètres des Mythiques ont été définis comme ceux par défaut."
L["Mythic+"] = "Mythique+"
L["Mythic+ setting changed to Default."] = "Les paramètres des Mythiques+ ont été définis comme ceux par défaut."
L["Name"] = "Nom"
L["Neck"] = "Cou"
L["New"] = "Nouveau"
L["New Sequence Name"] = "Nouveau nom de macro"
L["No"] = "Non"
L["No Active Version"] = "Aucune version active"
L["No changes were made to "] = "Aucune modification n'a été apportée à"
L["No Help Information "] = "Aucune information"
L["No Help Information Available"] = "Aucune information disponible"
L["No Sample Macros are available yet for this class."] = "Aucun exemple de macro n'est pour l'instant disponible pour cette classe."
L["No Sequences present so none displayed in the list."] = "Aucune macro n'est présente, donc aucune n'est affichée dans la liste."
L["Normal Colour"] = "Couleur normale"
L["Notes and help on how this macro works.  What things to remember.  This information is shown in the sequence browser."] = "Notes et informations sur le fonctionnement de cette macro. Celles-ci sont affichées dans la liste des macros."
L["On some clients the Editor will throw an error relating to setBackdrop. Turning this on will prevent those errors."] = "Sur certains clients WoW, l'éditeur renvoie une erreur relative à setBackdrop. Activer cette option empêchera ces erreurs."
L["Only Save Local Macros"] = "Enregistrer uniquement les macros locales"
--[[Translation missing --]]
L["OOC Queue Delay"] = "OOC Queue Delay"
L["Opens the GSE Options window"] = "Ouvre les options de GSE."
L["openviewer"] = "Ouvre le Visualiseur"
L["Options"] = "Options"
L["Options have been reset to defaults."] = "Les options ont été réinitialisées à leurs valeurs par défaut."
L["Output"] = "Sortie"
L["Output the action for each button press to verify StepFunction and spell availability."] = "Affiche l'action liée à chaque appui de bouton pour vérifier la disponibilité du sort et de la fonction StepFunction (TypeDeBoucle)."
L["Party"] = "Groupe"
L["Party setting changed to Default."] = "Les paramètres des Groupes ont été définis comme ceux par défaut."
L["Pause"] = "Pause"
L["Pause for the GCD."] = "Durée de la pause pour le GCD."
L["Paused"] = "En pause"
L["Paused - In Combat"] = "En pause - En combat"
L["Picks a Custom Colour for emphasis."] = "Choisit une couleur personnalisée pour l'emphase."
L["Picks a Custom Colour for the Author."] = "Choisit une couleur personnalisée pour l'auteur."
L["Picks a Custom Colour for the Commands."] = "Choisit une couleur personnalisée pour les commandes."
L["Picks a Custom Colour for the Mod Names."] = "Choisit une couleur personnalisée pour les noms de modificateurs."
L["Picks a Custom Colour to be used for braces and indents."] = "Sélectionne une couleur personnalisée à utiliser pour les accolades et les tabulations."
L["Picks a Custom Colour to be used for Icons."] = "Choisit une couleur personnalisée à utiliser pour les icônes."
L["Picks a Custom Colour to be used for language descriptors"] = "Choisit une couleur personnalisée à utiliser pour les descripteurs de langue."
L["Picks a Custom Colour to be used for macro conditionals eg [mod:shift]"] = "Choisit une couleur personnalisée à utiliser pour les conditions, par exemple [mod:shift]."
L["Picks a Custom Colour to be used for Macro Keywords like /cast and /target"] = "Choisit une couleur personnalisée à utiliser pour les commandes comme /cast et /target . "
L["Picks a Custom Colour to be used for numbers."] = "Choisit une couleur personnalisée à utiliser pour les nombres."
L["Picks a Custom Colour to be used for Spells and Abilities."] = "Choisit une couleur personnalisée à utiliser pour les sorts et les compétences."
L["Picks a Custom Colour to be used for StepFunctions."] = "Choisit une couleur personnalisée à utiliser pour StepFunction (TypeDeBoucle)."
L["Picks a Custom Colour to be used for strings."] = "Choisit une couleur personnalisée à utiliser pour les chaînes."
L["Picks a Custom Colour to be used for unknown terms."] = "Choisit une couleur personnalisée à utiliser pour les termes inconnus."
L["Picks a Custom Colour to be used normally."] = "Choisit une couleur personnalisée à utiliser pour les lignes normales."
L["Please wait till you have left combat before using the Sequence Editor."] = "Veuillez attendre d'avoir quitté le combat avant d'utiliser l'Editeur de Macro."
L["Plugins"] = "Plugins"
L["PostMacro"] = "PostMacro"
L["PreMacro"] = "PreMacro"
L["Prevent Sound Errors"] = "Empêcher les erreurs de son"
L["Prevent UI Errors"] = "Empêcher les erreurs d'interface"
L["Print KeyPress Modifiers on Click"] = "Afficher les modificateurs KeyPress lors des clics"
L["Print to the chat window if the alt, shift, control modifiers as well as the button pressed on each macro keypress."] = "Indique, dans la fenêtre de discussion, si le raccourci clavier associé à la macro a été activé et affiche si les touches Alt, Maj, Ctrl ont été utilisées."
L["Priority List (1 12 123 1234)"] = "Priorité (1 12 123 1234)"
L["Prompt Samples"] = "Charger les exemples"
L["PVP"] = "PVP"
L["PVP setting changed to Default."] = "Les paramètres pour le PVP ont été définis comme ceux par défaut."
L["Raid"] = "Raid"
L["Raid setting changed to Default."] = "Les paramètres des Raids ont été définis comme ceux par défaut."
L["Random - It will select .... a spell, any spell"] = "Aléatoire - Lance un sort au hasard"
L["Rank"] = "Rang"
L["Raw Edit"] = "Edition brute"
L["Ready to Send"] = "Prêt à envoyer"
L["Received Sequence "] = "Macro reçue"
L["Record"] = "Enregistrer"
L["Record Macro"] = "Enregistrer une macro"
L["Record the spells and items you use into a new macro."] = "Enregistrez les sorts et les objets que vous utilisez dans une nouvelle macro."
L["Registered Addons"] = "Plugins activés"
L["Rename New Macro"] = "Renommer la nouvelle macro"
L["Repeat"] = "Répéter"
L["Replace"] = "Remplacer"
L["Request Macro"] = "Demander une macro"
L["Request that the user sends you a copy of this macro."] = "Demander à l'utilisateur de vous envoyer une copie de cette macro."
L["Require Target to use"] = "A besoin d'une cible pour être utilisé"
L["Reset Macro when out of combat"] = "Réinitialiser la macro à la fin du combat"
L["Reset this macro when you exit combat."] = "Réinitialiser la macro à la fin du combat."
L["Resets"] = "Réinitialiser"
L["Resets macros back to the initial state when out of combat."] = "Réinitialise les macros à leur état initial lorsque le combat est terminé."
L["Restricted"] = "Limité"
L["RESTRICTED: Macro specifics disabled by author."] = "LIMITÉ : les spécificités des macros ont été désactivées par l'auteur."
L["Resume"] = "Reprendre"
--[[Translation missing --]]
L["Returns the current Loop Index.  If this is the third action in a loop it will return 3."] = "Returns the current Loop Index.  If this is the third action in a loop it will return 3."
L["Returns your current Global Cooldown value accounting for your haste if that stat is present."] = "Renvoie la valeur de votre GCD en tenant compte de votre hâte si cette statistique est présente."
L["Reverse Priority (1 21 321 4321)"] = "Priorité inversée (1 21 321 4321)"
L["Right Alt Key"] = "Touche Alt droite"
L["Right Control Key"] = "Touche Ctrl droite"
L["Right Mouse Button"] = "Bouton droit de la souris"
L["Right Shift Key"] = "Touche Maj droite"
L["Ring 1"] = "Anneau 1"
L["Ring 2"] = "Anneau 2"
L["Running"] = "En cours d'exécution"
L["Save"] = "Sauvegarder"
L["Save the changes made to this macro"] = "Enregistrer les modifications apportées à cette macro."
L["Scenario"] = "Scénario"
L["Scenario setting changed to Default."] = "Les paramètres des Scénarios ont été définis comme ceux par défaut."
L["Seconds"] = "Secondes"
L["Seed Initial Macro"] = "Diffuser la macro initiale"
L["Select a Sequence"] = "Sélectionnez une macro"
L["Select Other Version"] = "Selectionner une autre version"
L["Send"] = "Envoyer"
L["Send this macro to another GSE player who is on the same server as you are."] = "Envoyez cette macro à un autre utilisateur de GSE (à un autre joueur) qui se trouve sur le même serveur que vous."
L["Send To"] = "Envoyer à "
L["Sequence"] = "Séquence"
L["Sequence %s saved."] = "La macro %s a été enregistrée."
L["Sequence Author set to Unknown"] = "L'auteur de la macro défini comme \"Inconnu\""
L["Sequence Compare"] = "Comparaison de macros"
L["Sequence Debugger"] = "Débogueur de macro"
L["Sequence Editor"] = "Editeur de Macro"
L["Sequence Menu"] = "Liste de macros"
L["Sequence Name"] = "Nom de la macro"
L["Sequence Name %s is in Use. Please choose a different name."] = "La macro nommée %s est en cours d'utilisation. Veuillez choisir un autre nom."
L["Sequence Named %s was not specifically designed for this version of the game.  It may need adjustments."] = "La séquence nommée %s n'a pas été spécialement conçue pour cette version du jeu. Des ajustements peuvent être nécessaires."
L["Sequence Saved as version "] = "La macro a été enregistrée sous la version "
L["Sequence specID set to current spec of "] = "Le specID de la macro a été défini sur la spécification actuelle"
L["Sequence to Compress."] = "Macro à compresser."
L["Sequence Viewer"] = "Visualiseur de Macro"
L["Sequential (1 2 3 4)"] = "Séquentiel (1 2 3 4)"
L["Set Default Icon QuestionMark"] = "Définir l'icône par défaut (point d'interrogation)"
L["Shift Keys."] = "Touches Maj"
L["Show All Macros in Editor"] = "Afficher toutes les macros dans l'éditeur"
L["Show Class Macros in Editor"] = "Afficher les macros de votre classe dans l'éditeur"
L["Show Current Spells"] = "Montrer les sorts actuels"
L["Show Full Block Execution"] = "Montrer l'exécution complète du bloc"
L["Show Global Macros in Editor"] = "Afficher les macros globales dans l'éditeur"
L["Show GSE Users in LDB"] = "Afficher les utilisateurs de GSE dans le LDB"
L["Show OOC Queue in LDB"] = "Afficher la file d'attente OOC (Hors Combat) dans le LDB (LibDataBroker)"
L["Show the compiled version of this macro."] = "Affiche la version compilée de cette macro."
L["Show the current value of this variable."] = "Affiche la valeur actuelle de cette variable."
L["Source Language "] = "Langue source"
L["Specialisation / Class ID"] = "Spécialisation / Class ID"
L["Specialization Specific Macro"] = "Macro spécifique à la spécialisation"
L["SpecID/ClassID Colour"] = "Couleur des SpecID/ClassID"
--[[Translation missing --]]
L["Spell Cache Editor"] = "Spell Cache Editor"
L["Spell Colour"] = "Couleur des sorts"
--[[Translation missing --]]
L["Spell ID"] = "Spell ID"
--[[Translation missing --]]
L["Spell Name"] = "Spell Name"
--[[Translation missing --]]
L["State"] = "State"
L["Step Function"] = "Type de boucle"
L["Step Functions"] = "Types de boucle"
L["Stop"] = "Arrêter"
L["Store Debug Messages"] = "Stocker les messages de débogage"
L["Store output of debug messages in a Global Variable that can be referrenced by other mods."] = "Stocke la sortie des messages de débogage dans une variable globale qui peut être référencée par d'autres addons."
L["String Colour"] = "Couleur de la chaîne"
L["Support GSE"] = "Soutenir GSE"
L["Supporters"] = "Soutiens"
L["System Variables"] = "Variables système"
L["Talents"] = "Talents"
L["Target"] = "Cible"
L["Target language "] = "Langue cible"
L["Target protection is currently %s"] = "La protection de la cible est actuellement %s"
L["Test Variable"] = "Variable de test"
L["The author of this macro."] = "L'auteur de cette macro."
--[[Translation missing --]]
L[ [=[The block path shows the direct location of a block.  This can be edited to move a block to a different position quickly.  Each block is prefixed by its container.
EG 2.3 means that the block is the third block in a container at level 2.  You can move a block into a container block by specifying the parent block.  You need to press the Okay button to move the block.]=] ] = [=[The block path shows the direct location of a block.  This can be edited to move a block to a different position quickly.  Each block is prefixed by its container.
EG 2.3 means that the block is the third block in a container at level 2.  You can move a block into a container block by specifying the parent block.  You need to press the Okay button to move the block.]=]
L["The command "] = "La commande"
L["The current result of variable |cff0000ff~~%s~~|r is |cFF00D1FF%s|r"] = "Le résultat actuel de la variable |cff0000ff~~%s~~|r est |cFF00D1FF%s|r"
L["The Custom StepFunction Specified is not recognised and has been ignored."] = "La StepFunction (TypeDeBoucle).spécifiée n'a pas été reconnue et a été ignorée."
L["The default sizes of each window."] = "La taille par défaut de chaque fenêtre."
--[[Translation missing --]]
L["The delay in seconds between Out of Combat Queue Polls.  The Out of Combat Queue saves changes and updates macros.  When you hit save or change zones, these actions enter a queue which checks that first you are not in combat before proceeding to complete their task.  After checking the queue it goes to sleep for x seconds before rechecking what is in the queue."] = "The delay in seconds between Out of Combat Queue Polls.  The Out of Combat Queue saves changes and updates macros.  When you hit save or change zones, these actions enter a queue which checks that first you are not in combat before proceeding to complete their task.  After checking the queue it goes to sleep for x seconds before rechecking what is in the queue."
L["The following people donate monthly via Patreon for the ongoing maintenance and development of GSE.  Their support is greatly appreciated."] = "Les personnes suivantes participent au développement de GSE en faisant un don mensuel sur Patreon. Leur soutien est grandement apprécié."
L["The GSE Out of Combat queue is %s"] = "La file d'attente \"hors combat\" de GSE est %s"
L["The GUI has not been loaded.  Please activate this plugin amongst WoW's addons to use the GSE GUI."] = "L'interface graphique n'a pas été chargée. Veuillez activer ce plugin parmi les addons de WoW pour utiliser l'interface graphique GSE."
--[[Translation missing --]]
L["The GUI is corrupt.  Please ensure that your GSE install is complete."] = "The GUI is corrupt.  Please ensure that your GSE install is complete."
--[[Translation missing --]]
L["The GUI is missing.  Please ensure that your GSE install is complete."] = "The GUI is missing.  Please ensure that your GSE install is complete."
--[[Translation missing --]]
L["The GUI needs updating.  Please ensure that your GSE install is complete."] = "The GUI needs updating.  Please ensure that your GSE install is complete."
L["The Macro Translator will translate an English sequence to your local language for execution.  It can also be used to translate a sequence into a different language.  It is also used for syntax based colour markup of Sequences in the editor."] = "Le Traducteur de Macro traduira une macro écrite à la base en Anglais vers votre langue (Français) pour que la macro puisse être exécutée. Il peut également être utilisé pour traduire une séquence dans une autre langue. Il est également utilisé pour afficher certaines parties des séquences dans différentes couleurs."
L["The main lines of the macro."] = [=[Ce bloc contient les lignes principales de la macro.
Il est possible de lancer ces lignes X fois en boucle : pour cela, changez la valeur de "Boucle Interne".
Voici une vidéo (en anglais) de TimothyLuke qui explique le fonctionnement de KeyPressed, PreMacro, Sequence, PostMacro, KeyRelease : https://youtu.be/VNcDuFzfihs]=]
L["The milliseconds being used in key click delay."] = "Valeur en millisecondes utilisée pour la fréquence des clics."
L[ [=[The name of your macro.  This name has to be unique and can only be used for one object.
You can copy this entire macro by changing the name and choosing Save.]=] ] = "Le nom de votre macro. Ce nom doit être unique et ne peut être utilisé que pour un seul objet. \\nVous pouvez copier toute cette macro en changeant le nom et en choisissant Enregistrer."
L["The Sample Macros have been reloaded."] = "Les exemples de macros ont été rechargés."
L["The Sequence Editor can attempt to parse the Sequences, KeyPress and KeyRelease in realtime.  This is still experimental so can be turned off."] = "L'Editeur de Macro peut tenter d'analyser le bloc Séquence, KeyPress et KeyRelease en temps réel. Ceci est encore expérimental et peut donc être désactivé."
L["The Sequence Editor is an addon for GnomeSequencer-Enhanced that allows you to view and edit Sequences in game.  Type "] = "L'Editeur de Macro est un module complémentaire pour GnomeSequencer-Enhanced qui vous permet de visualiser et d'éditer les macros en jeu. Tapez"
L[ [=[The step function determines how your macro executes.  Each time you click your macro GSE will go to the next line.  
The next line it chooses varies.  If Random then it will choose any line.  If Sequential it will go to the next line.  
If Priority it will try some spells more often than others.]=] ] = "Le type de boucle détermine comment votre macro s'exécute. A chaque fois que vous cliquerez sur l'icône de votre macro, GSE ira à la ligne suivante. \\nLa ligne suivante qu'il choisit varie selon cette option. Priorité : il essaiera certains sorts plus souvent que d'autres. Aléatoire : il choisira n'importe quelle ligne. Séquentiel : il passera à la ligne suivante."
L["The version of this macro that will be used when you enter raids."] = "La version de cette macro qui sera utilisée lorsque vous ferez des raids."
L["The version of this macro that will be used where no other version has been configured."] = "La version de cette macro qui sera utilisée si aucune autre version n'a été configurée."
L["The version of this macro to use in Arenas.  If this is not specified, GSE will look for a PVP version before the default."] = "La version de cette macro à utiliser dans les arènes. Si rien n'est spécifié, GSE recherchera une version PVP avant la version par défaut."
L["The version of this macro to use in heroic dungeons."] = "La version de cette macro à utiliser dans les donjons héroïques."
L["The version of this macro to use in Mythic Dungeons."] = "La version de cette macro à utiliser dans les donjons mythiques."
L["The version of this macro to use in Mythic+ Dungeons."] = "La version de cette macro à utiliser dans les donjons mythiques +."
L["The version of this macro to use in normal dungeons."] = "La version de cette macro à utiliser dans les donjons mode normal."
L["The version of this macro to use in PVP."] = "La version de cette macro à utiliser en PVP."
L["The version of this macro to use in Scenarios."] = "La version de cette macro à utiliser dans les scénarios."
L["The version of this macro to use when in a party in the world."] = "La version de cette macro à utiliser en groupe partout ailleurs."
L["The version of this macro to use when in time walking dungeons."] = "La version de cette macro à utiliser dans les donjons des Marcheurs du Temps."
L["There are %i events in out of combat queue"] = "Il y a %i événements dans la file d'attente \"hors combat\""
L["There are no events in out of combat queue"] = "Il n'y a pas d'événements dans la file d'attente \"hors combat\""
L["There are No Macros Loaded for this class.  Would you like to load the Sample Macro?"] = "Aucune macro n'est chargée pour cette classe. Souhaitez-vous charger les exemples de macros ?"
L["There is an issue with sequence %s.  It has not been loaded to prevent the mod from failing."] = "Il y a un problème avec la macro %s. Elle n'a pas été chargée pour empêcher l'addon de planter."
L[ [=[These lines are executed after the lines in the Sequence Box have been repeated Inner Loop Limit number of times.
The Sequence will then go on to the PreMacro if it exists then back to the Sequence.]=] ] = "Les lignes dans \"PostMacro\" sont exécutées une fois toutes les lignes dans \"Séquence\" terminées \\n (et répétées un nombre de fois indiqué dans \"Boucle Interne\"). Une fois \"Séquence\" et \"PostMacro\" terminés, \\n la macro passe ensuite à \"PreMacro\" si elle existe, puis reviendra à \"Séquence\" et ainsi de suite..."
L[ [=[These lines are executed before the lines in the Sequence Box.  If an Inner Loop Limit is not set, these are executed only once.  
If an Inner Loop Limit has been set these are executed after the Sequence has been looped through the number of times.  
The Sequence will then go on to the Post Macro if it exists then back to the PreMacro.]=] ] = "Les lignes dans \"PreMacro\" sont exécutées avant les lignes ajoutées dans \"Séquence\". Si vous ne \\n mettez rien dans la case \"Boucle Interne\", les lignes dans \"PreMacro\" ne seront exécutées qu'une seule \\n fois, au début puis la macro passera à \"Séquence\". \\n Si vous souhaitez lancer les sorts de \"Séquence\" \\n plusieurs fois en boucle, ajoutez le nombre de boucles voulu dans \"Boucle Interne\". Dans ce cas, les lignes \\n dans \"PreMacro\" seront exécutées au début de votre macro, puis la macro passera à \"Séquence\" (X fois), \\n puis passera à \"PostMacro\" et reviendra à \"PreMacro\", etc..."
L["These lines are executed every time you click this macro.  They are evaluated by WOW after the line in the Sequence Box."] = "Ces lignes sont exécutées à chaque fois que vous relâchez la touche du raccourci clavier. Ces lignes sont prises en compte par WOW après les lignes qui sont dans \"Séquence\"."
L["These lines are executed every time you click this macro.  They are evaluated by WOW before the line in the Sequence Box."] = "Ces lignes sont exécutées à chaque fois que vous appuyez sur la touche du raccourci clavier. Ces lignes sont prises en compte par WOW avant les lignes qui sont dans \"Séquence\"."
L["These options combine to allow you to reset a macro while it is running.  These options are Cumulative ie they add to each other.  Options Like LeftClick and RightClick won't work together very well."] = "Ces options se combinent pour vous permettre de réinitialiser une macro pendant son exécution. Ces options sont cumulatives, c'est-à-dire qu'elles s'ajoutent les unes aux autres. Des options comme Clic Gauche et Clic Droit ne fonctionneront pas très bien ensemble."
L["These tick boxes have three settings for each slot.  Gold = Definately use this item. Blank = Do not use this item automatically.  Silver = Either use or not based on my default settings store in GSE's Options."] = "Ces cases à cocher ont trois paramètres pour chaque emplacement. \\nOr = Utiliser cet objet. Vide = Ne pas utiliser automatiquement cet object. Argent = Utiliser ou non en fonction des paramètres par défaut dans les options de GSE."
L["This box is disabled as no Inner Loop Limit has been set.  It will never be called without it."] = "Cette case est désactivée car aucune \"Boucle Interne\" n'a été définie."
L["This change will not come into effect until you save this macro."] = "Cette modification n'entrera en vigueur que lorsque vous enregistrerez cette macro. "
--[[Translation missing --]]
L["This CVAR makes WoW use your abilities when you press the key not when you release it.  To use GSE in its native configuration this needs to be checked."] = "This CVAR makes WoW use your abilities when you press the key not when you release it.  To use GSE in its native configuration this needs to be checked."
--[[Translation missing --]]
L["This function will clear the spell cache and any mappings between individual spellIDs and spellnames.."] = "This function will clear the spell cache and any mappings between individual spellIDs and spellnames.."
--[[Translation missing --]]
L["This function will open a window enabling you to edit the spell cache and any mappings between individual spellIDs and spellnames.."] = "This function will open a window enabling you to edit the spell cache and any mappings between individual spellIDs and spellnames.."
L["This function will remove the SHIFT+N, ALT+N and CTRL+N keybindings for this character.  Useful if [mod:shift] etc conditions don't work in game."] = "Cette fonction supprime les raccourcis clavier MAJ+N, ALT+N et CTRL+N pour ce perso. Utile si les conditions [mod:shift] etc ne fonctionnent pas dans le jeu. "
L["This function will update macro stubs to support listening to the options below.  This is required to be completed 1 time per character."] = "Cette fonction met à jour les emplacements de macro pour prendre en charge les options ci-dessous. Ceci doit être complété 1 fois par personnage."
L["This is a small addon that allows you create a sequence of macros to be executed at the push of a button."] = "Il s'agit d'un petit addon qui vous permet de créer une suite de macros à exécuter en appuyant successivement sur un bouton."
--[[Translation missing --]]
L["This is needed for ConsolePort and BindPad."] = "This is needed for ConsolePort and BindPad."
L["This is the only version of this macro.  Delete the entire macro to delete this version."] = "C'est la seule version de cette macro. Supprimez complètement la macro pour supprimer cette version. "
L["This macro uses features that are not available in this version. You need to update GSE to %s in order to use this macro."] = "Cette macro utilise des fonctionnalités qui ne sont pas disponibles dans cette version. Vous devez mettre à jour GSE vers %s afin d'utiliser cette macro."
L["This option clears errors and stack traces ingame.  This is the equivalent of /run UIErrorsFrame:Clear() in a KeyRelease.  Turning this on will trigger a Scam warning about running custom scripts."] = "Cette option efface les erreurs dans le jeu. C'est l'équivalent de /run UIErrorsFrame:Clear() dans un KeyRelease. L'activation de cette option déclenche un avertissement concernant l'exécution de scripts personnalisés."
L["This option dumps extra trace information to your chat window to help troubleshoot problems with the mod"] = "Cette option affiche des informations supplémentaires dans la fenêtre de discussion pour vous aider à résoudre les problèmes avec l'addon."
L["This option hide error sounds like \"That is out of range\" from being played while you are hitting a GS Macro.  This is the equivalent of /console Sound_EnableErrorSpeech lines within a Sequence.  Turning this on will trigger a Scam warning about running custom scripts."] = "Cette option empêche les erreurs sonores telles que \"Je ne suis pas à portée\" pendant que vous utilisez une macro GSE. C'est l'équivalent de la ligne /console Sound_EnableErrorSpeech dans une séquence. L'activation de cette option déclenche un avertissement concernant l'exécution de scripts personnalisés."
L["This option hides text error popups and dialogs and stack traces ingame.  This is the equivalent of /script UIErrorsFrame:Hide() in a KeyRelease.  Turning this on will trigger a Scam warning about running custom scripts."] = "Cette option masque les fenêtres d'erreur dans le jeu. C'est l'équivalent de /script UIErrorsFrame:Hide() dans un KeyRelease. L'activation de cette option déclenche un avertissement concernant l'exécution de scripts personnalisés."
L["This option prevents macros firing unless you have a target. Helps reduce mistaken targeting of other mobs/groups when your target dies."] = "Cette option empêche les macros de se lancer à moins que vous n'ayez une cible. Aide à réduire le ciblage par erreur d'autres mobs lorsque votre cible meurt."
L["This sequence is Read Only and unable to be edited."] = "Cette macro est en lecture seule et ne peut pas être modifiée."
L["This Sequence was exported from GSE %s."] = "Cette macro a été exportée depuis GSE %s."
--[[Translation missing --]]
L["This setting forces the ActionButtonUseKeyDown setting one way or another.  It also reconfigures GSE's Macro Stubs to operate in the specified mode."] = "This setting forces the ActionButtonUseKeyDown setting one way or another.  It also reconfigures GSE's Macro Stubs to operate in the specified mode."
L["This shows the Global Macros available as well as those for your class."] = "Ceci montre les macros globales disponibles ainsi que celles de votre classe."
L["This version has been modified by TimothyLuke to make the power of GnomeSequencer avaialble to people who are not comfortable with lua programming."] = [=[GnomeSequencer a été modifié par TimothyLuke pour permettre à tous ceux qui ne sont pas à l'aise avec la programmation lua de créer des macros. 
]=]
L["This will display debug messages for the "] = "Ceci affichera des messages de débogage pour le "
L["This will display debug messages for the GSE Ingame Transmission and transfer"] = [=[Ceci affichera les messages de débogage pour la transmission et le transfert GSE
]=]
L["This will display debug messages in the Chat window."] = "Ceci affichera les messages de débogage dans la fenêtre de discussion."
L["Timewalking"] = "Marcheurs Du Temps"
L["Timewalking setting changed to Default."] = "Le paramètre Marcheurs Du Temps a été changé comme valeur par défaut."
L["Title Colour"] = "Couleur du titre"
L["To correct this either delete the version via the GSE Editor or enter the following command to delete this macro totally.  %s/run GSE.DeleteSequence (%i, %s)%s"] = "Pour corriger cela, supprimez la version via l'Editeur de Macro de GSE ou entrez la commande suivante pour supprimer totalement cette macro. %s/run GSE.DeleteSequence (%i, %s)%s"
L["To get started "] = "Pour commencer"
L["To use a macro, open the macros interface and create a macro with the exact same name as one from the list.  A new macro with two lines will be created and place this on your action bar."] = "Pour utiliser une macro, ouvrez l'interface des macros et créez une macro avec exactement le même nom qu'une de la liste. Une nouvelle macro avec deux lignes sera créée et placez-la sur votre barre d'action."
L["Translate to"] = "Traduire vers"
L["Translated Sequence"] = "Macro traduite"
L["Trinket 1"] = "Bijou 1"
L["Trinket 2"] = "Bijou 2"
--[[Translation missing --]]
L["Troubleshooting"] = "Troubleshooting"
L["Two sequences with unknown sources found."] = "Deux macros avec des sources inconnues ont été trouvées."
L["Unable to interpret sequence."] = "Impossible de déchiffrer la macro."
L["Unable to process content.  Fix table and try again."] = "Impossible de traiter le contenu. Corrigez le tableau et réessayez."
L["Unknown Author|r "] = "Auteur inconnu|r"
L["Unknown Colour"] = "Couleur inconnue"
--[[Translation missing --]]
L["Unrecognised Import"] = "Unrecognised Import"
--[[Translation missing --]]
L["Up forces GSE into ActionButtonUseKeyDown=0 while Down forces GSE into ActionButtonUseKeyDown=1"] = "Up forces GSE into ActionButtonUseKeyDown=0 while Down forces GSE into ActionButtonUseKeyDown=1"
L["Update"] = "Mettre à jour"
L["Update Macro Stubs"] = "Mettre à jour les emplacements de macro"
L["Update Macro Stubs."] = "Mettre à jour les emplacements de macro"
--[[Translation missing --]]
L["Update Talents"] = "Update Talents"
--[[Translation missing --]]
L["Update the stored talents to match the current chosen talents."] = "Update the stored talents to match the current chosen talents."
L["Updated Macro"] = "Macro mise à jour"
L["UpdateSequence"] = "MiseAJourDeLaMacro"
L["Updating due to new version."] = "Mise à jour en raison de la nouvelle version."
L["Use"] = "Utiliser"
L["Use Belt Item in KeyRelease"] = "Utiliser la ceinture dans KeyRelease"
L["Use External MS Timings"] = "Utiliser la vitesse de rafraîchissement du clic"
L["Use First Ring in KeyRelease"] = "Utiliser le premier anneau dans KeyRelease"
L["Use First Trinket in KeyRelease"] = "Utiliser le premier bijou dans KeyRelease"
L["Use Global Account Macros"] = "Utiliser les macros globales du compte"
L["Use Head Item in KeyRelease"] = "Utiliser l'objet de tête dans KeyRelease"
L["Use Macro Translator"] = "Utiliser le Traducteur de Macro"
L["Use Neck Item in KeyRelease"] = "Utiliser l'objet de cou dans KeyRelease"
L["Use Realtime Parsing"] = "Utiliser l'analyse temps réel"
L["Use Second Ring in KeyRelease"] = "Utiliser le deuxième anneau dans KeyRelease"
L["Use Second Trinket in KeyRelease"] = "Utiliser le deuxième bijou dans KeyRelease"
L["Use Verbose Export Sequence Format"] = "Exporter la macro de façon détaillée"
L["Use WLM Export Sequence Format"] = "Exporter la macro au format WLM"
L["Value"] = "Valeur"
L["Variables"] = "Variables"
L["Version"] = "Version"
L["Version="] = "Version ="
--[[Translation missing --]]
L["Virtual Button Support"] = "Virtual Button Support"
L["WARNING ONLY"] = "AVERTISSEMENT"
--[[Translation missing --]]
L["was unable to be interpreted."] = "was unable to be interpreted."
L["was unable to be programmed.  This macro will not fire until errors in the macro are corrected."] = "n'a pas pu être programmé. Cette macro ne se déclenchera pas tant que les erreurs de la macro ne seront pas corrigées."
L["WeakAuras"] = "WeakAuras"
L["WeakAuras is a mod that watches for certain conditions and actions and they alerts the player to them occuring.  These are included for convenience and still need to be copied from here and imported to the WeakAuras mod via the command /wa."] = "WeakAuras est un addon qui surveille ce qui se passe pendant les combats et alerte le joueur lorsque ses sorts sont prêts à être lancés. Ces WeakAuras sont inclus par commodité mais doivent toujours être copiés à partir d'ici et importés dans l'addon WeakAuras via la commande /wa."
L["WeakAuras was not found."] = "WeakAuras n'a pas été trouvé."
L["WeakAuras was not found.  Reported error was %s"] = "WeakAuras n'a pas été trouvé. L'erreur générée était %s"
L["Website or forum URL where a player can get more information or ask questions about this macro."] = "Site web ou forum où un joueur pourra obtenir plus d'informations sur cette macro ou poser des questions sur son fonctionnement."
L[ [=[What are the preferred talents for this macro?
'1,2,3,1,2,3,1' means First row choose the first talent, Second row choose the second talent etc]=] ] = "Quels sont les talents préférés pour cette macro ? Chaque chiffre correspond à une ligne dans la fenêtre des talents (N). \\n'3,1,2,2,1,3,2' signifie que la première rangée a le 3ème talent sélectionné. \\nLa deuxième rangée a le 1er talent sélectionné. La 3ème rangée a le 2ème talent sélectionné, etc."
L["What class or spec is this macro for?  If it is for all classes choose Global."] = "A quelle classe ou spécification cette macro est-elle destinée ? Si c'est pour toutes les classes, choisissez Global."
L["When creating a macro, if there is not a personal character macro space, create an account wide macro."] = "Lors de la création d'une macro, s'il n'y a plus d'espace disponible dans les macros du personnage, mettre la macro dans les macros globales du compte."
L["When debugging the output of a sequence, show the full executed block in the Debugger Output."] = "Lors du débogage de la sortie d'une séquence, afficher le bloc pleinement exécuté dans la sortie du débogueur."
L["When exporting a sequence create a stub entry to import for WLM's Website."] = "Lors de l'exportation d'une macro, créer un emplacement de macro pour le site web WLM."
L["When exporting a sequence use a human readable verbose form."] = "Lors de l'exportation d'une macro, utiliser une version lisible."
L["When GSE imports a macro and it already exists locally and has local edits, what do you want the default action to be.  Merge - Add the new MacroVersions to the existing Macro.  Replace - Replace the existing macro with the new version. Ignore - ignore updates.  This default action will set the default on the Compare screen however if the GUI is not available this will be the action taken."] = "Lorsque GSE importe une macro alors qu'elle existe déjà sur votre disque (avec des modifications), quelle doit être l'action par défaut ? Fusionner : ajoute les changements à la macro existante. Remplacer : remplace la macro existante par la nouvelle version. Ignorer : ignore les mises à jour. Cette action définira la valeur par défaut sur l'écran Comparer, mais si l'interface graphique n'est pas disponible, ce sera l'action choisie."
L["When loading or creating a sequence, if it is a global or the macro has an unknown specID automatically create the Macro Stub in Account Macros"] = "Lors du chargement ou lors de la création d'une macro, s'il s'agit d'une macro globale ou si la macro a un specID inconnu, créer automatiquement l'emplacement de macro dans les macros du compte."
L["When loading or creating a sequence, if it is a macro of the same class automatically create the Macro Stub"] = "Lors du chargement ou de la création d'une macro, s'il s'agit d'une macro de la même classe, créer automatiquement l'emplacement de macro."
L["When you log into a class without any macros, prompt to load the sample macros."] = "Lorsque vous ouvrez GSE et que celui-ci n'a aucune macro, ceci vous invite à charger des macros d'exemple."
L["Window Sizes"] = "Taille des fenêtres"
L["Yes"] = "Oui"
L["You cannot delete the Default version of this macro.  Please choose another version to be the Default on the Configuration tab."] = "Vous ne pouvez pas supprimer la version par Défaut de cette macro. SVP, choisissez une autre version pour être celle par Défaut dans l'onglet de Configuration."
L["You cannot delete this version of a sequence.  This version will be reloaded as it is contained in "] = "Vous ne pouvez pas supprimer cette version de macro. Cette version sera rechargée telle qu'elle est enregistrée dans"
L["You need to reload the User Interface for the change in StepFunction to take effect.  Would you like to do this now?"] = "Vous devez relancer l'interface du jeu pour que le changement dans StepFunction (TypeDeBoucle).soit effectif. Voulez-vous le faire maintenant ?"
L["You need to reload the User Interface to complete this task.  Would you like to do this now?"] = "Vous devez relancer l'interface du jeu pour finir cette tâche. Voulez-vous le faire maintenant ?"
L["Your ClassID is "] = "Votre ClassID est"
L["Your current Specialisation is "] = "Votre spécialisation actuelle est"
L["Your sequence name was longer than 27 characters.  It has been shortened from %s to %s so that your macro will work."] = "Votre nom de macro faisait plus de 27 caractères. Il a été raccourci de %s à %s pour que votre macro puisse fonctionner."


